from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import smtplib


deputados = ({'Nome' : 'ABEL SALVADOR MESQUITA JUNIOR' , 'Email' : 'dep.abelmesquitajr@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSE ADAIL CARNEIRO SILVA' , 'Email' : 'dep.adailcarneiro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ADALBERTO CAVALCANTI RODRIGUES' , 'Email' : 'dep.adalbertocavalcanti@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ADELMO CARNEIRO LEAO' , 'Email' : 'dep.adelmocarneiroleao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ADELSON BARRETO DOS SANTOS' , 'Email' : 'dep.adelsonbarreto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ADEMIR CAMILO PRATES RODRIGUES' , 'Email' : 'dep.ademircamilo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ADILTON DOMINGOS SACHETTI' , 'Email' : 'dep.adiltonsachetti@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AELTON JOSÉ DE FREITAS' , 'Email' : 'dep.aeltonfreitas@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AFONSO BANDEIRA FLORENCE' , 'Email' : 'dep.afonsoflorence@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ ALFONSO EBERT HAMM' , 'Email' : 'dep.afonsohamm@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AFONSO ANTUNES DA MOTTA' , 'Email' : 'dep.afonsomotta@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AGUINALDO VELLOSO BORGES RIBEIRO' , 'Email' : 'dep.aguinaldoribeiro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALAN RICK MIRANDA' , 'Email' : 'dep.alanrick@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ ALBERTO OLIVEIRA VELOSO FILHO' , 'Email' : 'dep.albertofilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOÃO ALBERTO FRAGA SILVA' , 'Email' : 'dep.albertofraga@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALCEU MOREIRA DA SILVA' , 'Email' : 'dep.alceumoreira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALESSANDRO LUCCIOLA MOLON' , 'Email' : 'dep.alessandromolon@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALEX CANZIANI SILVEIRA' , 'Email' : 'dep.alexcanziani@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALEX SPINELLI MANENTE' , 'Email' : 'dep.alexmanente@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALEXANDRE BALDY DE SANT ANNA BRAGA' , 'Email' : 'dep.alexandrebaldy@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALEXANDRE LEITE DA SILVA' , 'Email' : 'dep.alexandreleite@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALEXANDRE AUGUSTUS SERFIOTIS' , 'Email' : 'dep.alexandreserfiotis@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALEXANDRE VALLE CARDOSO' , 'Email' : 'dep.alexandrevalle@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JACOB ALFREDO STOFFELS KAEFER' , 'Email' : 'dep.alfredokaefer@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALFREDO PEREIRA DO NASCIMENTO' , 'Email' : 'dep.alfredonascimento@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALICE MAZZUCO PORTUGAL' , 'Email' : 'dep.aliceportugal@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ALIEL MACHADO BARK' , 'Email' : 'dep.alielmachado@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALTINEU CÔRTES FREITAS COUTINHO' , 'Email' : 'dep.altineucortes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ALUISIO GUIMARAES MENDES FILHO' , 'Email' : 'dep.aluisiomendes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANA LUCIA LIPPAUS PERUGINI' , 'Email' : 'dep.anaperugini@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ANDRE DOS SANTOS ABDON' , 'Email' : 'dep.andreabdon@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANDRÉ AUGUSTO CASTRO DO AMARAL FILHO' , 'Email' : 'dep.andreamaral@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANDRÉ CARLOS ALVES DE PAULA FILHO' , 'Email' : 'dep.andredepaula@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANDRÉ PEIXOTO FIGUEIREDO LIMA' , 'Email' : 'dep.andrefigueiredo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANDRE LUIZ CARVALHO RIBEIRO' , 'Email' : 'dep.andrefufuca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANDRÉ LUIS DANTAS FERREIRA' , 'Email' : 'dep.andremoura@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANDRES NAVARRO SANCHEZ' , 'Email' : 'dep.andressanchez@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RAIMUNDO ANGELIM VASCONCELOS' , 'Email' : 'dep.angelim@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANÍBAL FERREIRA GOMES' , 'Email' : 'dep.anibalgomes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO LUIZ PARANHOS RIBEIRO LEITE DE BRITO' , 'Email' : 'dep.antoniobrito@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO CARLOS MARTINS DE BULHÕES' , 'Email' : 'dep.antoniobulhoes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO CARLOS DE MENDES THAME' , 'Email' : 'dep.antoniocarlosmendesthame@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO JACOME DE LIMA JUNIOR' , 'Email' : 'dep.antoniojacome@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO ARIOSTO HOLANDA' , 'Email' : 'dep.ariostoholanda@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ARLINDO CHIGNALIA JUNIOR' , 'Email' : 'dep.arlindochinaglia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ARNALDO FARIA DE SÁ' , 'Email' : 'dep.arnaldofariadesa@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ARNALDO JORDY FIGUEIREDO' , 'Email' : 'dep.arnaldojordy@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AROLDE DE OLIVEIRA' , 'Email' : 'dep.aroldedeoliveira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ARTHUR CÉSAR PEREIRA DE LIRA' , 'Email' : 'dep.arthurlira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ARTHUR DE OLIVEIRA MAIA DA SILVA' , 'Email' : 'dep.arthuroliveiramaia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ARTHUR VIRGILIO DO CARMO RIBEIRO BISNETO' , 'Email' : 'dep.arthurvirgiliobisneto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO DE ASSIS CARVALHO GONÇALVES' , 'Email' : 'dep.assiscarvalho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ASSIS MIGUEL DO COUTO' , 'Email' : 'dep.assisdocouto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ASSIS FLÁVIO DA SILVA MELO' , 'Email' : 'dep.assismelo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ÁTILA SIDNEY LINS ALBUQUERQUE' , 'Email' : 'dep.atilalins@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ÁTILA FREITAS LIRA' , 'Email' : 'dep.atilalira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AUGUSTO SILVEIRA DE CARVALHO' , 'Email' : 'dep.augustocarvalho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AUGUSTO RODRIGUES COUTINHO DE MELO' , 'Email' : 'dep.augustocoutinho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'AUREO LIDIO MOREIRA RIBEIRO' , 'Email' : 'dep.aureo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAO CARLOS BACELAR BATISTA' , 'Email' : 'dep.bacelar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ FELIPE BALEIA TENUTO ROSSI' , 'Email' : 'dep.baleiarossi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ADALBERTO SOUZA GALVÃO' , 'Email' : 'dep.bebeto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'BENEDITA SOUZA DA SILVA SAMPAIO' , 'Email' : 'dep.beneditadasilva@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'BENITO DA GAMA SANTOS' , 'Email' : 'dep.benitogama@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'BENJAMIN GOMES MARANHÃO NETO' , 'Email' : 'dep.benjaminmaranhao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HEBERTE LAMARCK GOMES DA SILVA' , 'Email' : 'dep.betinhogomes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ ROBERTO OLIVEIRA FARO' , 'Email' : 'dep.betofaro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO ROBERTO GOMES MANSUR' , 'Email' : 'dep.betomansur@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS ALBERTO DE SOUSA ROSADO SEGUNDO' , 'Email' : 'dep.betorosado@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROBERTO SALAME FILHO' , 'Email' : 'dep.betosalame@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'OLAVO BILAC PINTO NETO' , 'Email' : 'dep.bilacpinto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ELVINO JOSÉ BOHN GASS' , 'Email' : 'dep.bohngass@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'BONIFÁCIO JOSÉ TAMM DE ANDRADA' , 'Email' : 'dep.bonifaciodeandrada@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'BRUNA DIAS FURLAN' , 'Email' : 'dep.brunafurlan@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'BRUNIELE FERREIRA GOMES' , 'Email' : 'dep.brunny@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'BENEVENUTO DACIOLO FONSECA DOS SANTOS' , 'Email' : 'dep.cabodaciolo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FLAVIO ALVES SABINO' , 'Email' : 'dep.cabosabino@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ GIONILSON PINHEIRO BORGES' , 'Email' : 'dep.cabucuborges@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS FELIPE VAZQUEZ DE SOUZA LEÃO' , 'Email' : 'dep.cacaleao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ CARLOS CAETANO' , 'Email' : 'dep.caetano@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CAIO NARCIO RODRIGUES DA SILVEIRA' , 'Email' : 'dep.caionarcio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CAJAR ONESIMO RIBEIRO NARDES' , 'Email' : 'dep.cajarnardes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSE AUGUSTO ROSA' , 'Email' : 'dep.capitaoaugusto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS AUGUSTO ANDRADE SILVA' , 'Email' : 'dep.carlosandrade@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS GOMES BEZERRA' , 'Email' : 'dep.carlosbezerra@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS EDUARDO CINTRA DA COSTA PEREIRA' , 'Email' : 'dep.carloseduardocadoca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO CARLOS GOMES DA SILVA' , 'Email' : 'dep.carlosgomes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS HENRIQUE AMORIM' , 'Email' : 'dep.carloshenriquegaguim@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS HUMBERTO MANNATO' , 'Email' : 'dep.carlosmanato@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS EDUARDO XAVIER MARUN' , 'Email' : 'dep.carlosmarun@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS DO CARMO ANDRADE MELLES' , 'Email' : 'dep.carlosmelles@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS HENRIQUE FOCESI SAMPAIO' , 'Email' : 'dep.carlossampaio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS ALBERTO ROLIM ZARATTINI' , 'Email' : 'dep.carloszarattini@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARMEN EMÍLIA BONFÁ ZANOTTO' , 'Email' : 'dep.carmenzanotto@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'CELIO ANTONIO DA SILVEIRA' , 'Email' : 'dep.celiosilveira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CELSO ALENCAR RAMOS JACOB' , 'Email' : 'dep.celsojacob@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CELSO MALDANER' , 'Email' : 'dep.celsomaldaner@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CELSO PANSERA' , 'Email' : 'dep.celsopansera@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CELSO UBIRAJARA RUSSOMANNO' , 'Email' : 'dep.celsorussomanno@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CESAR HANNA HALUM' , 'Email' : 'dep.cesarhalum@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS CESAR CORREIA DE MESSIAS' , 'Email' : 'dep.cesarmessias@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'César Antonio de Souza' , 'Email' : 'dep.cesarsouza@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO RODRIGUES DE ALENCAR FILHO' , 'Email' : 'dep.chicoalencar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO JOSÉ D ANGELO PINTO' , 'Email' : 'dep.chicodangelo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO LOPES DA SILVA' , 'Email' : 'dep.chicolopes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CHRISTIANE DE SOUZA YARED' , 'Email' : 'dep.christianedesouzayared@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JOSÉ CÍCERO SOARES DE ALMEIDA' , 'Email' : 'dep.ciceroalmeida@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CLÁUDIO CAJADO SAMPAIO' , 'Email' : 'dep.claudiocajado@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CLEBER VERDE CORDEIRO MENDES' , 'Email' : 'dep.cleberverde@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARIA DA CONCEICAO SAMPAIO MOURA' , 'Email' : 'dep.conceicaosampaio@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'LUIS ANTONIO FRANCISCATTO COVATTI' , 'Email' : 'dep.covattifilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CLEUZA PEREIRA DO NASCIMENTO' , 'Email' : 'dep.creuzapereira@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'CRISTIANE BRASIL FRANCISCO' , 'Email' : 'dep.cristianebrasil@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'DAGOBERTO NOGUEIRA FILHO' , 'Email' : 'dep.dagobertonogueira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DAMIÃO FELICIANO DA SILVA' , 'Email' : 'dep.damiaofeliciano@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DAMINA DE CARVALHO PEREIRA' , 'Email' : 'dep.daminapereira@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'DANIEL GOMES DE ALMEIDA' , 'Email' : 'dep.danielalmeida@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DANIEL PIRES COELHO' , 'Email' : 'dep.danielcoelho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DANIEL ELIAS CARVALHO VILELA' , 'Email' : 'dep.danielvilela@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DANILO JORGE DE BARROS CABRAL' , 'Email' : 'dep.danilocabral@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO DANILO BASTOS FORTE' , 'Email' : 'dep.daniloforte@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DANRLEI DE DEUS HINTERHOLZ' , 'Email' : 'dep.danrleidedeushinterholz@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DARCÍSIO PAULO PERONDI' , 'Email' : 'dep.darcisioperondi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DAVIDSON DE MAGALHÃES SANTOS' , 'Email' : 'dep.davidsonmagalhaes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DÉCIO NERY DE LIMA' , 'Email' : 'dep.deciolima@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DEJORGE PATRICIO DA SILVA' , 'Email' : 'dep.dejorgepatricio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDER MAURO CARDOSO BARRA' , 'Email' : 'dep.delegadoedermauro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDSON MOREIRA DA SILVA' , 'Email' : 'dep.delegadoedsonmoreira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FERNANDO DESTITO FRANCISCHINI' , 'Email' : 'dep.delegadofrancischini@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WALDIR SOARES DE OLIVEIRA' , 'Email' : 'dep.delegadowaldir@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WANDERLEY ALVES DE OLIVEIRA' , 'Email' : 'dep.deley@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DEOCLIDES ANTONIO SANTOS NETO MACEDO' , 'Email' : 'dep.deoclidesmacedo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DIEGO LEONARDO DE ANDRADE CARVALHO' , 'Email' : 'dep.diegoandrade@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DIEGO ALEXSANDER GONCALO PAULA GARCIA' , 'Email' : 'dep.diegogarcia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DILCEU JOÃO SPERAFICO' , 'Email' : 'dep.dilceusperafico@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DIMAS FABIANO TOLEDO JÚNIOR' , 'Email' : 'dep.dimasfabiano@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DOMINGOS GOMES DE AGUIAR NETO' , 'Email' : 'dep.domingosneto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DOMINGOS SÁVIO CAMPOS RESENDE' , 'Email' : 'dep.domingossavio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JORGE SILVA' , 'Email' : 'dep.dr.jorgesilva@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SINVAL MALHEIROS PINTO JÚNIOR' , 'Email' : 'dep.dr.sinvalmalheiros@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DULCE FERREIRA PAGANI MIRANDA' , 'Email' : 'dep.dulcemiranda@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ÉDIO VIEIRA LOPES' , 'Email' : 'dep.ediolopes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDMAR DE SOUZA ARRUDA' , 'Email' : 'dep.edmararruda@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDMILSON BRITO RODRIGUES' , 'Email' : 'dep.edmilsonrodrigues@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDUARDO LUIZ BARROS BARBOSA' , 'Email' : 'dep.eduardobarbosa@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDUARDO NANTES BOLSONARO' , 'Email' : 'dep.eduardobolsonaro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDUARDO PEDROSA CURY' , 'Email' : 'dep.eduardocury@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EDUARDO HENRIQUE DA FONTE DE ALBUQUERQUE SILVA' , 'Email' : 'dep.eduardodafonte@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EFRAIM DE ARAÚJO MORAIS FILHO' , 'Email' : 'dep.efraimfilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ELCIONE THEREZINHA ZAHLUTH BARBALHO' , 'Email' : 'dep.elcionebarbalho@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ADRIANO ELI CORRÊA' , 'Email' : 'dep.elicorreafilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ELIZEU DIONIZIO SOUZA  DA SILVA' , 'Email' : 'dep.elizeudionizio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ELIZIANE PEREIRA GAMA FERREIRA' , 'Email' : 'dep.elizianegama@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ELMAR JOSE VIEIRA NASCIMENTO' , 'Email' : 'dep.elmarnascimento@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ENIO JOSÉ VERRI' , 'Email' : 'dep.enioverri@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ÉRIKA JUCÁ KOKAY' , 'Email' : 'dep.erikakokay@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ERIVELTON LIMA SANTANA' , 'Email' : 'dep.eriveltonsantana@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EROS FERREIRA BIONDINI' , 'Email' : 'dep.erosbiondini@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ESPERIDIÃO AMIN HELOU FILHO' , 'Email' : 'dep.esperidiaoamin@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EVAIR VIEIRA DE MELO' , 'Email' : 'dep.evairvieirademelo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EVANDRO HERRERA BERTONE GUSSI' , 'Email' : 'dep.evandrogussi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EVANDRO ROGERIO ROMAN' , 'Email' : 'dep.evandroroman@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EXPEDITO GONCALVES FERREIRA NETTO' , 'Email' : 'dep.expeditonetto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EZEQUIEL ANGELO FONSECA' , 'Email' : 'dep.ezequielfonseca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'EZEQUIEL CORTAZ TEIXEIRA' , 'Email' : 'dep.ezequielteixeira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FÁBIO SALUSTINO MESQUITA DE FARIA' , 'Email' : 'dep.fabiofaria@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FABIO PAULINO GARCIA' , 'Email' : 'dep.fabiogarcia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FABIO CRUZ MITIDIERI' , 'Email' : 'dep.fabiomitidieri@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FÁBIO AUGUSTO RAMALHO DOS SANTOS' , 'Email' : 'dep.fabioramalho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FABIO DE ALMEIDA REIS' , 'Email' : 'dep.fabioreis@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FABIO FERNANDES DE SOUSA' , 'Email' : 'dep.fabiosousa@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FAUSTO RUY PINATO' , 'Email' : 'dep.faustopinato@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FELIPE LEONE BORNIER DE OLIVEIRA' , 'Email' : 'dep.felipebornier@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FELIPE CATALÃO MAIA' , 'Email' : 'dep.felipemaia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FELIX DE ALMEIDA MENDONÇA JÚNIOR' , 'Email' : 'dep.felixmendoncajunior@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FERNANDO MONTEIRO DE ALBUQUERQUE' , 'Email' : 'dep.fernandomonteiro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FLÁVIA CARREIRO ALBUQUERQUE MORAIS' , 'Email' : 'dep.flaviamorais@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'FLAVIANO FLÁVIO BAPTISTA DE MELO' , 'Email' : 'dep.flavianomelo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FLAVIO AUGUSTO DA SILVA' , 'Email' : 'dep.flavinho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO ALVES DE AGUIAR' , 'Email' : 'dep.franciscochapadinha@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO FLORIANO DE SOUSA SILVA' , 'Email' : 'dep.franciscofloriano@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANKLIN ROBERTO DE LIMA SOUZA' , 'Email' : 'dep.franklin@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GABRIEL GUIMARÃES DE ANDRADE' , 'Email' : 'dep.gabrielguimaraes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GENECIAS MATEUS NORONHA' , 'Email' : 'dep.geneciasnoronha@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GEORGE HILTON DOS SANTOS CECÍLIO' , 'Email' : 'dep.georgehilton@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GEOVANIA DE SA RODRIGUES' , 'Email' : 'dep.geovaniadesa@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'GERALDO RESENDE PEREIRA' , 'Email' : 'dep.geraldoresende@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FERNANDO LÚCIO GIACOBO' , 'Email' : 'dep.giacobo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GILBERTO NASCIMENTO SILVA' , 'Email' : 'dep.gilbertonascimento@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GIOVANI CHERINI' , 'Email' : 'dep.giovanicherini@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GIUSEPPE VECCI' , 'Email' : 'dep.giuseppevecci@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GIVALDO DE SÁ GOUVEIA' , 'Email' : 'dep.givaldocarimbao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GIVALDO VIEIRA DA SILVA' , 'Email' : 'dep.givaldovieira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GLAUBER DE MEDEIROS BRAGA' , 'Email' : 'dep.glauberbraga@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ GONZAGA PATRIOTA' , 'Email' : 'dep.gonzagapatriota@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARIA GORETE PEREIRA' , 'Email' : 'dep.goretepereira@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ANTONIO GOULART DOS REIS' , 'Email' : 'dep.goulart@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GUILHERME CRUZ DE SOUZA COELHO' , 'Email' : 'dep.guilhermecoelho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GUILHERME MUSSI FERREIRA' , 'Email' : 'dep.guilhermemussi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HEITOR JOSE SCHUCH' , 'Email' : 'dep.heitorschuch@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HELDER IGNACIO SALOMAO' , 'Email' : 'dep.heldersalomao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HELIO LEITE DA SILVA' , 'Email' : 'dep.helioleite@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HENRIQUE FONTANA JÚNIOR' , 'Email' : 'dep.henriquefontana@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HERÁCLITO DE SOUSA FORTES' , 'Email' : 'dep.heraclitofortes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HERCULANO CASTILHO PASSOS JUNIOR' , 'Email' : 'dep.herculanopassos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HERMES PARCIANELLO' , 'Email' : 'dep.hermesparcianello@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HEULER ABREU CRUVINEL' , 'Email' : 'dep.heulercruvinel@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HILDO AUGUSTO DA ROCHA NETO' , 'Email' : 'dep.hildorocha@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HIRAN MANUEL GONCALVES DA SILVA' , 'Email' : 'dep.hirangoncalves@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HISSA NAGIB ABRAHAO FILHO' , 'Email' : 'dep.hissaabrahao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HUGO LEAL MELO DA SILVA' , 'Email' : 'dep.hugoleal@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HUGO MOTTA WANDERLEY DA NÓBREGA' , 'Email' : 'dep.hugomotta@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'IRACEMA MARIA PORTELLA NUNES NOGUEIRA LIMA' , 'Email' : 'dep.iracemaportella@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'IRAJÁ SILVESTRE FILHO' , 'Email' : 'dep.irajaabreu@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO LAZARO SILVA' , 'Email' : 'dep.irmaolazaro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'IVAN VALENTE' , 'Email' : 'dep.ivanvalente@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'IZALCI LUCAS FERREIRA' , 'Email' : 'dep.izalcilucas@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'IZAQUE JOSE DA SILVA' , 'Email' : 'dep.izaquesilva@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JAIME MARTINS FILHO' , 'Email' : 'dep.jaimemartins@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JAIR MESSIAS BOLSONARO' , 'Email' : 'dep.jairbolsonaro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JANDIRA FEGHALI' , 'Email' : 'dep.jandirafeghali@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JANETE MARIA GÓES CAPIBERIBE' , 'Email' : 'dep.janetecapiberibe@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'Jarbas de Andrade Vasconcelos' , 'Email' : 'dep.jarbasvasconcelos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JEAN WYLLYS DE MATOS SANTOS' , 'Email' : 'dep.jeanwyllys@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JEFFERSON ALVES DE CAMPOS' , 'Email' : 'dep.jeffersoncampos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JERÔNIMO PIZZOLOTTO GOERGEN' , 'Email' : 'dep.jeronimogoergen@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JESSICA ROJAS SALES' , 'Email' : 'dep.jessicasales@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JOAO HENRIQUE HOLANDA  CALDAS' , 'Email' : 'dep.jhc@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOHNATHAN PEREIRA DE JESUS' , 'Email' : 'dep.jhonatandejesus@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARIA DO SOCORRO JÔ MORAES' , 'Email' : 'dep.jomoraes@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JOÃO JOSÉ DE ARRUDA JÚNIOR' , 'Email' : 'dep.joaoarruda@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOÃO CAMPOS DE ARAÚJO' , 'Email' : 'dep.joaocampos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOÃO CARLOS PAOLILO BACELAR FILHO' , 'Email' : 'dep.joaocarlosbacelar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAO SOMARIVA DANIEL' , 'Email' : 'dep.joaodaniel@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAO DERLY DE OLIVEIRA NUNES JUNIOR' , 'Email' : 'dep.joaoderly@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAO FERNANDO PONTUAL COUTINHO' , 'Email' : 'dep.joaofernandocoutinho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAO GUALBERTO VASCONCELOS' , 'Email' : 'dep.joaogualberto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOÃO MARCELO SANTOS SOUZA' , 'Email' : 'dep.joaomarcelosouza@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAO PAULO KARAM KLEINUBING' , 'Email' : 'dep.joaopaulokleinubing@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAO PAULO TAVARES PAPA' , 'Email' : 'dep.joaopaulopapa@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOÃO RODRIGUES' , 'Email' : 'dep.joaorodrigues@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOAQUIM PASSARINHO PINTO DE SOUZA PORTO' , 'Email' : 'dep.joaquimpassarinho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JONES ALEXANDRE MARTINS' , 'Email' : 'dep.jonesmartins@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JONY MARCOS DE SOUZA ARAUJO' , 'Email' : 'dep.jonymarcos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JORGE CATARINO LEONARDELI BOEIRA' , 'Email' : 'dep.jorgeboeira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JORGE WICKS CÔRTE REAL' , 'Email' : 'dep.jorgecortereal@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JORGE JOSE SANTOS PEREIRA SOLLA' , 'Email' : 'dep.jorgesolla@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JORGE TADEU MUDALEN' , 'Email' : 'dep.jorgetadeumudalen@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JORGINHO DOS SANTOS MELLO' , 'Email' : 'dep.jorginhomello@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ AIRTON FÉLIX CIRILO DA SILVA' , 'Email' : 'dep.joseairtoncirilo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ CARLOS ALELUIA COSTA' , 'Email' : 'dep.josecarlosaleluia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ CARLOS LEÃO DE ARAÚJO' , 'Email' : 'dep.josecarlosaraujo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ ALBERTO FOGAÇA DE MEDEIROS' , 'Email' : 'dep.josefogaca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ NOBRE GUIMARÃES' , 'Email' : 'dep.joseguimaraes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ MENTOR GUILHERME DE MELLO NETTO' , 'Email' : 'dep.josementor@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ NUNES SOARES' , 'Email' : 'dep.josenunes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ OTÁVIO GERMANO' , 'Email' : 'dep.joseotaviogermano@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ BENITO PRIANTE JÚNIOR' , 'Email' : 'dep.josepriante@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'José Reinaldo Carneiro Tavares' , 'Email' : 'dep.josereinaldo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ ALVES ROCHA' , 'Email' : 'dep.joserocha@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSE LUIZ STÉDILE' , 'Email' : 'dep.josestedile@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSINIANE BRAGA NUNES' , 'Email' : 'dep.josinunes@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JOSUÉ BENGTSON' , 'Email' : 'dep.josuebengtson@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOVAIR DE OLIVEIRA ARANTES' , 'Email' : 'dep.jovairarantes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOZIANE ARAUJO NASCIMENTO' , 'Email' : 'dep.joziaraujo@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JULIA MARIA GODINHO DA CRUZ MARINHO' , 'Email' : 'dep.juliamarinho@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JÚLIO CÉSAR DE CARVALHO LIMA' , 'Email' : 'dep.juliocesar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JÚLIO CÉSAR DELGADO' , 'Email' : 'dep.juliodelgado@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JULIO LUIZ BAPTISTA LOPES' , 'Email' : 'dep.juliolopes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO DA CRUZ FILGUEIRA JUNIOR' , 'Email' : 'dep.juniormarreca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSE JUSCELINO DOS SANTOS REZENDE FILHO' , 'Email' : 'dep.juscelinofilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JUTAHY MAGALHÃES JÚNIOR' , 'Email' : 'dep.jutahyjunior@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'IOLANDA KEIKO MIASHIRO OTA' , 'Email' : 'dep.keikoota@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'LAERCIO JOSÉ DE OLIVEIRA' , 'Email' : 'dep.laerciooliveira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LAERTE RODRIGUES DE BESSA' , 'Email' : 'dep.laertebessa@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LAUDIVIO ALVARENGA CARVALHO' , 'Email' : 'dep.laudiviocarvalho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARIA LAURA MONTEZA DE SOUZA CARNEIRO' , 'Email' : 'dep.lauracarneiro@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'LÁZARO BOTELHO MARTINS' , 'Email' : 'dep.lazarobotelho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LEANDRE DAL PONTE' , 'Email' : 'dep.leandre@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'WELINGTON COIMBRA' , 'Email' : 'dep.lelocoimbra@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LEONARDO CUNHA DE BRITO' , 'Email' : 'dep.leodebrito@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ LEONARDO COSTA MONTEIRO' , 'Email' : 'dep.leonardomonteiro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LEONARDO LEMOS BARROS QUINTÃO' , 'Email' : 'dep.leonardoquintao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ LEÔNIDAS DE MENEZES CRISTINO' , 'Email' : 'dep.leonidascristino@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LEOPOLDO COSTA MEYER' , 'Email' : 'dep.leopoldomeyer@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LINCOLN DINIZ PORTELA' , 'Email' : 'dep.lincolnportela@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LINDOMAR BARBOSA ALVES' , 'Email' : 'dep.lindomargarcon@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO ADOLPHO LOBBE NETO' , 'Email' : 'dep.lobbeneto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUANA MARIA DA SILVA COSTA' , 'Email' : 'dep.luanacosta@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'LUCAS DE CASTRO SANTOS' , 'Email' : 'dep.lucasvergilio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUCIANA BARBOSA DE OLIVEIRA SANTOS' , 'Email' : 'dep.lucianasantos@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'LUCIANO CALDAS BIVAR' , 'Email' : 'dep.lucianobivar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUCIANO DUCCI' , 'Email' : 'dep.lucianoducci@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUCIO ANTONIO MOSQUINI' , 'Email' : 'dep.luciomosquini@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LÚCIO DUTRA VALE' , 'Email' : 'dep.luciovale@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LÚCIO QUADROS VIEIRA LIMA' , 'Email' : 'dep.luciovieiralima@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIS CARLOS HEINZE' , 'Email' : 'dep.luiscarlosheinze@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIS HENRIQUE DE OLIVEIRA RESENDE' , 'Email' : 'dep.luistibe@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ CARLOS JORGE HAULY' , 'Email' : 'dep.luizcarloshauly@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ CARLOS RAMOS' , 'Email' : 'dep.luizcarlosramos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ CLAUDIO PEREIRA ALVES' , 'Email' : 'dep.luizclaudio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ ALBUQUERQUE COUTO' , 'Email' : 'dep.luizcouto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ FERNANDO RAMOS FARIA' , 'Email' : 'dep.luizfernandofaria@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ LAURO FERREIRA FILHO' , 'Email' : 'dep.luizlaurofilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ HILOSHI NISHIMORI' , 'Email' : 'dep.luiznishimori@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ SÉRGIO NÓBREGA DE OLIVEIRA' , 'Email' : 'dep.luizsergio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZA ERUNDINA DE SOUSA' , 'Email' : 'dep.luizaerundina@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'LUIZIANNE DE OLIVEIRA LINS' , 'Email' : 'dep.luiziannelins@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JOSE MARIA MACEDO JUNIOR' , 'Email' : 'dep.macedo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MAGDA MOFATTO HON' , 'Email' : 'dep.magdamofatto@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JOSÉ DE ANDRADE MAIA FILHO' , 'Email' : 'dep.maiafilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SERGIO OLIMPIO GOMES' , 'Email' : 'dep.majorolimpio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ HENRIQUE MANDETTA' , 'Email' : 'dep.mandetta@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARA CRISTINA GABRILLI' , 'Email' : 'dep.maragabrilli@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'MARCELO THEODORO DE AGUIAR' , 'Email' : 'dep.marceloaguiar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCELO HENRIQUE TEIXEIRA DIAS' , 'Email' : 'dep.marceloalvaroantonio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCELO GUILHERME DE ARO FERREIRA' , 'Email' : 'dep.marceloaro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCELO COSTA E CASTRO' , 'Email' : 'dep.marcelocastro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCELO JANDRE DELAROLI' , 'Email' : 'dep.marcelodelaroli@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCELO VIVIANI GONÇALVES' , 'Email' : 'dep.marcelomatos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCELO SQUASSONI' , 'Email' : 'dep.marcelosquassoni@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCIO LUIZ ALVINO DE SOUZA' , 'Email' : 'dep.marcioalvino@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MÁRCIO CARLOS MARINHO' , 'Email' : 'dep.marciomarinho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCO ANTONIO NEVES CABRAL' , 'Email' : 'dep.marcoantoniocabral@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCO AURÉLIO SPALL MAIA' , 'Email' : 'dep.marcomaia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCO ANTONIO TEBALDI' , 'Email' : 'dep.marcotebaldi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'DIONILSO MATEUS MARCON' , 'Email' : 'dep.marcon@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCOS ABRAO RORIZ SOARES DE CARVALHO' , 'Email' : 'dep.marcosabrao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCOS MONTES CORDEIRO' , 'Email' : 'dep.marcosmontes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCOS JOSE REATEGUI SOUZA' , 'Email' : 'dep.marcosreategui@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCOS ROGÉRIO DA SILVA BRITO' , 'Email' : 'dep.marcosrogerio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCOS BEZERRA RIBEIRO SOARES' , 'Email' : 'dep.marcossoares@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCUS VINÍCIUS CAETANO PESTANA DA SILVA' , 'Email' : 'dep.marcuspestana@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCUS ANTÔNIO VICENTE' , 'Email' : 'dep.marcusvicente@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARIA MARGARIDA MARTINS SALOMÃO' , 'Email' : 'dep.margaridasalomao@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'MARIA DO ROSÁRIO NUNES' , 'Email' : 'dep.mariadorosario@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'MARIA HELENA VERONESE RODRIGUES' , 'Email' : 'dep.mariahelena@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'MARIANA FONSECA RIBEIRO CARVALHO DE MORAES' , 'Email' : 'dep.marianacarvalho@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'MARINALDO ROSENDO DE ALBUQUERQUE' , 'Email' : 'dep.marinaldorosendo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARINHA CÉLIA ROCHA RAUPP DE MATOS' , 'Email' : 'dep.marinharaupp@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'MÁRIO LÚCIO HERINGER' , 'Email' : 'dep.marioheringer@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARIO SILVIO MENDES NEGROMONTE JUNIOR' , 'Email' : 'dep.marionegromontejr@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MAURO RIBEIRO LOPES' , 'Email' : 'dep.maurolopes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MAURO MARIANI' , 'Email' : 'dep.mauromariani@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MAURO PEREIRA' , 'Email' : 'dep.mauropereira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MIGUEL MOUBADDA HADDAD' , 'Email' : 'dep.miguelhaddad@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MIGUEL LOMBARDI' , 'Email' : 'dep.miguellombardi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MILTON ANTONIO CASQUEL MONTI' , 'Email' : 'dep.miltonmonti@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MIRO TEIXEIRA' , 'Email' : 'dep.miroteixeira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MISAEL ARTUR FERREIRA VARELLA' , 'Email' : 'dep.misaelvarella@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ OLIMPIO SILVEIRA MORAES' , 'Email' : 'dep.missionariojoseolimpio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MOISES DINIZ LIMA' , 'Email' : 'dep.moisesdiniz@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MOSES HAENDEL MELO RODRIGUES' , 'Email' : 'dep.mosesrodrigues@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NELSON MARQUEZELLI' , 'Email' : 'dep.nelsonmarquezelli@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NELSON MEURER' , 'Email' : 'dep.nelsonmeurer@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NELSON PADOVANI' , 'Email' : 'dep.nelsonpadovani@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NELSON VICENTE PORTELA PELLEGRINO' , 'Email' : 'dep.nelsonpellegrino@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NEWTON CARDOSO JUNIOR' , 'Email' : 'dep.newtoncardosojr@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NILSON APARECIDO LEITÃO' , 'Email' : 'dep.nilsonleitao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NILSON PINTO DE OLIVEIRA' , 'Email' : 'dep.nilsonpinto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NILTO IGNACIO TATTO' , 'Email' : 'dep.niltotatto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NILTON BALBINO' , 'Email' : 'dep.niltoncapixaba@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NIVALDO FERREIRA DE ALBUQUERQUE NETO' , 'Email' : 'dep.nivaldoalbuquerque@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'NORMA AYUB ALVES' , 'Email' : 'dep.normaayub@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'LUIZ ODORICO MONTEIRO DE ANDRADE' , 'Email' : 'dep.odoricomonteiro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ONYX DORNELLES LORENZONI' , 'Email' : 'dep.onyxlorenzoni@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ORLANDO SILVA DE JESUS JUNIOR' , 'Email' : 'dep.orlandosilva@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'OSMAR STUART BERTOLDI' , 'Email' : 'dep.osmarbertoldi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'OSMAR JOSÉ SERRAGLIO' , 'Email' : 'dep.osmarserraglio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'OTAVIO SANTOS SILVA LEITE' , 'Email' : 'dep.otavioleite@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOÃO CARLOS SIQUEIRA' , 'Email' : 'dep.padrejoao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ FRANCISCO PAES LANDIM' , 'Email' : 'dep.paeslandim@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO EURICO DA SILVA' , 'Email' : 'dep.pastoreurico@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUCIANO FRED BRAGA PENHA' , 'Email' : 'dep.pastorlucianobraga@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PATRUS ANANIAS DE SOUSA' , 'Email' : 'dep.patrusananias@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAUDERNEY TOMAZ AVELINO' , 'Email' : 'dep.pauderneyavelino@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO FERNANDO DOS SANTOS' , 'Email' : 'dep.paulao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO ABI-ACKEL' , 'Email' : 'dep.pauloabiackel@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO VELLOSO DANTAS AZI' , 'Email' : 'dep.pauloazi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO FERNANDO FEIJO TORRES' , 'Email' : 'dep.paulofeijo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO ROBERTO FOLETTO' , 'Email' : 'dep.paulofoletto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO ROBERTO FREIRE DA COSTA' , 'Email' : 'dep.paulofreire@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO HENRIQUE ELLERY LUSTOSA DA COSTA' , 'Email' : 'dep.paulohenriquelustosa@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO SÉRGIO PARANHOS DE MAGALHÃES' , 'Email' : 'dep.paulomagalhaes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO SALIM MALUF' , 'Email' : 'dep.paulomaluf@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO PEREIRA DA SILVA' , 'Email' : 'dep.paulopereiradasilva@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PAULO ROBERTO SEVERO PIMENTA' , 'Email' : 'dep.paulopimenta@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ PAULO TEIXEIRA FERREIRA' , 'Email' : 'dep.pauloteixeira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PEDRO PINHEIRO CHAVES' , 'Email' : 'dep.pedrochaves@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PEDRO OLIVEIRA CUNHA LIMA' , 'Email' : 'dep.pedrocunhalima@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PEDRO FERNANDES RIBEIRO' , 'Email' : 'dep.pedrofernandes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PEDRO PAULO CARVALHO TEIXEIRA' , 'Email' : 'dep.pedropaulo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PEDRO FRANCISCO UCZAI' , 'Email' : 'dep.pedrouczai@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'PEDRO TORRES BRANDÃO VILELA' , 'Email' : 'dep.pedrovilela@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'GILBERTO JOSÉ SPIER VARGAS' , 'Email' : 'dep.pepevargas@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'POLLYANA FATIMA GAMA SANTOS' , 'Email' : 'dep.pollyanagama@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'DARCI POMPEO DE MATTOS' , 'Email' : 'dep.pompeodemattos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARCO ANTÔNIO FELICIANO' , 'Email' : 'dep.pr.marcofeliciano@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VICTORIO GALLI FILHO' , 'Email' : 'dep.professorvictoriogalli@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'MARIA AUXILIADORA SEABRA REZENDE' , 'Email' : 'dep.professoradorinhaseabrarezende@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'MARCIVANIA DO SOCORRO DA ROCHA FLEXA' , 'Email' : 'dep.professoramarcivania@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'RAFAEL HUETE DA MOTTA' , 'Email' : 'dep.rafaelmotta@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RAIMUNDO GOMES DE MATOS' , 'Email' : 'dep.raimundogomesdematos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'TANIA RAQUEL DE QUEIROZ MUNIZ' , 'Email' : 'dep.raquelmuniz@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'REGINALDO LÁZARO DE OLIVEIRA LOPES' , 'Email' : 'dep.reginaldolopes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'REINHOLD STEPHANES' , 'Email' : 'dep.reinholdstephanes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'REMIDIO MONAI MONTESSI' , 'Email' : 'dep.remidiomonai@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RENATA HELLMEISTER DE ABREU' , 'Email' : 'dep.renataabreu@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'RENATO BARBOSA DE ANDRADE' , 'Email' : 'dep.renatoandrade@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RENATO DELMAR MOLLING' , 'Email' : 'dep.renatomolling@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RENZO DO AMARAL BRAZ' , 'Email' : 'dep.renzobraz@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RICARDO IZAR JUNIOR' , 'Email' : 'dep.ricardoizar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RICARDO TEOBALDO CAVALCANTI' , 'Email' : 'dep.ricardoteobaldo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ RICARDO ALVARENGA TRIPOLI' , 'Email' : 'dep.ricardotripoli@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'BENEDITO ROBERTO ALVES FERREIRA' , 'Email' : 'dep.robertoalves@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROBERTO EGÍDIO BALESTRA' , 'Email' : 'dep.robertobalestra@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROBERTO PEREIRA DE BRITTO' , 'Email' : 'dep.robertobritto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROBERTO ALVES DE LUCENA' , 'Email' : 'dep.robertodelucena@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROBERTO JOÃO PEREIRA FREIRE' , 'Email' : 'dep.robertofreire@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO ROBERTO RODRIGUES GÓES DA SILVA' , 'Email' : 'dep.robertogoes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROBERTO DA SILVA SALES' , 'Email' : 'dep.robertosales@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROBINSON SANTOS ALMEIDA' , 'Email' : 'dep.robinsonalmeida@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WHERLES FERNANDES DA ROCHA' , 'Email' : 'dep.rocha@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RODRIGO BATISTA DE CASTRO' , 'Email' : 'dep.rodrigodecastro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RODRIGO FELINTO IBARRA EPITÁCIO MAIA' , 'Email' : 'dep.rodrigomaia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RODRIGO RODRIGUES DE SOUZA MARTINS' , 'Email' : 'dep.rodrigomartins@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RODRIGO OTAVIO SOARES PACHECO' , 'Email' : 'dep.rodrigopacheco@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROGÉRIO SIMONETTI MARINHO' , 'Email' : 'dep.rogeriomarinho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROGÉRIO MENDONÇA' , 'Email' : 'dep.rogeriopeninhamendonca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROGÉRIO SCHUMANN ROSSO' , 'Email' : 'dep.rogeriorosso@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROGÉRIO SILVA SANTOS' , 'Email' : 'dep.rogeriosilva@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RÔMULO JOSÉ DE GOUVEIA' , 'Email' : 'dep.romulogouveia@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RONALDO JOSÉ BENEDET' , 'Email' : 'dep.ronaldobenedet@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RONALDO CARLETTO' , 'Email' : 'dep.ronaldocarletto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RONALDO FONSECA DE SOUZA' , 'Email' : 'dep.ronaldofonseca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RONALDO AUGUSTO LESSA SANTOS' , 'Email' : 'dep.ronaldolessa@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RONALDO MANCHADO MARTINS' , 'Email' : 'dep.ronaldomartins@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RÔNEY TANIOS NEMER' , 'Email' : 'dep.roneynemer@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ROSANGELA DE SOUZA GOMES' , 'Email' : 'dep.rosangelagomes@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'ROSEANE CAVALCANTE DE FREITAS ESTRELA' , 'Email' : 'dep.rosinhadaadefal@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'RUBENS BUENO' , 'Email' : 'dep.rubensbueno@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RUBENS OTONI GOMIDE' , 'Email' : 'dep.rubensotoni@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RUBENS PEREIRA E SILVA JUNIOR' , 'Email' : 'dep.rubenspereirajunior@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'RAIMUNDO SABINO CASTELO BRANCO MAUÉS' , 'Email' : 'dep.sabinocastelobranco@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SÁGUAS MORAES SOUSA' , 'Email' : 'dep.saguasmoraes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SANDRO ALEX CRUZ DE OLIVEIRA' , 'Email' : 'dep.sandroalex@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ SARAIVA FELIPE' , 'Email' : 'dep.saraivafelipe@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SÉRGIO LUÍS LACERDA BRITO' , 'Email' : 'dep.sergiobrito@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SÉRGIO IVAN MORAES' , 'Email' : 'dep.sergiomoraes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SERGIO BAVINI' , 'Email' : 'dep.sergioreis@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SERGIO DE SOUZA' , 'Email' : 'dep.sergiosouza@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO SERGIO ALVES VIDIGAL' , 'Email' : 'dep.sergiovidigal@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SERGIO ZVEITER' , 'Email' : 'dep.sergiozveiter@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SEVERINO DE SOUZA SILVA' , 'Email' : 'dep.severinoninho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SHÉRIDAN ESTÉRFANY OLIVEIRA DE ANCHIETA' , 'Email' : 'dep.sheridan@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'SILAS CÂMARA' , 'Email' : 'dep.silascamara@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SILAS FREIRE PEREIRA E SILVA' , 'Email' : 'dep.silasfreire@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SÍLVIO SERAFIM COSTA' , 'Email' : 'dep.silviocosta@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SILVIO FRANÇA TORRES' , 'Email' : 'dep.silviotorres@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SIMÃO SESSIM' , 'Email' : 'dep.simaosessim@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SIMONE MARIA MORGADO FERREIRA' , 'Email' : 'dep.simonemorgado@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'SORAYA ALENCAR DOS SANTOS' , 'Email' : 'dep.sorayasantos@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'SOSTENES SILVA CAVALCANTE' , 'Email' : 'dep.sostenescavalcante@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'STEFANO AGUIAR DOS SANTOS' , 'Email' : 'dep.stefanoaguiar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'LUIZ GONZAGA RIBEIRO' , 'Email' : 'dep.subtenentegonzaga@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO TADEU BARBOSA DE ALENCAR' , 'Email' : 'dep.tadeualencar@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'HIDEKAZU TAKAYAMA' , 'Email' : 'dep.takayama@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'SERGIO LUCIO DE ALMEIDA' , 'Email' : 'dep.tenentelucio@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'TEREZA CRISTINA CORREA DA COSTA DIAS' , 'Email' : 'dep.terezacristina@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'THIAGO MELLO PEIXOTO DA SILVEIRA' , 'Email' : 'dep.thiagopeixoto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO EVERARDO OLIVEIRA SILVA' , 'Email' : 'dep.tiririca@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTÔNIO PINHEIRO JÚNIOR' , 'Email' : 'dep.toninhopinheiro@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTONIO WANDSCHEER' , 'Email' : 'dep.toninhowandscheer@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ULDURICO ALENCAR PINTO' , 'Email' : 'dep.ulduricojunior@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'FRANCISCO VAIDON OLIVEIRA' , 'Email' : 'dep.vaidonoliveira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ANTÔNIO CARLOS VALADARES FILHO' , 'Email' : 'dep.valadaresfilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VALDIR COLATTO' , 'Email' : 'dep.valdircolatto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VALMIR CARLOS DA ASSUNÇÃO' , 'Email' : 'dep.valmirassuncao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VALMIR PRASCIDELLI' , 'Email' : 'dep.valmirprascidelli@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VANDER LUIZ DOS SANTOS LOUBET' , 'Email' : 'dep.vanderloubet@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VANDERLEI MACRIS' , 'Email' : 'dep.vanderleimacris@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VENEZIANO VITAL DO RÊGO SEGUNDO NETO' , 'Email' : 'dep.venezianovitaldorego@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VICENTE CÂNDIDO DA SILVA' , 'Email' : 'dep.vicentecandido@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VICENTE PAULO DA SILVA' , 'Email' : 'dep.vicentinho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VICENTE ALVES DE OLIVEIRA JUNIOR' , 'Email' : 'dep.vicentinhojunior@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'CARLOS VICTOR GUTERRES MENDES' , 'Email' : 'dep.victormendes@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VINICIUS RAPOZO DE CARVALHO' , 'Email' : 'dep.viniciuscarvalho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VINICIUS DE AZEVEDO GURGEL' , 'Email' : 'dep.viniciusgurgel@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VITOR LIPPI' , 'Email' : 'dep.vitorlippi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'VITOR PEREIRA VALIM' , 'Email' : 'dep.vitorvalim@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WADIH NEMER DAMOUS FILHO' , 'Email' : 'dep.wadihdamous@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WALDENOR ALVES PEREIRA FILHO' , 'Email' : 'dep.waldenorpereira@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WALDIR MARANHÃO CARDOSO' , 'Email' : 'dep.waldirmaranhao@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WALNEY DA ROCHA CARVALHO' , 'Email' : 'dep.walneyrocha@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WALTER PEREIRA ALVES' , 'Email' : 'dep.walteralves@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WALTER SHINDI IIHOSHI' , 'Email' : 'dep.walterihoshi@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WELITON FERNANDES PRADO' , 'Email' : 'dep.welitonprado@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ WELLINGTON ROBERTO' , 'Email' : 'dep.wellingtonroberto@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WEVERTON ROCHA MARQUES DE SOUSA' , 'Email' : 'dep.wevertonrocha@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WILSON SILVA BESERRA' , 'Email' : 'dep.wilsonbeserra@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ WILSON SANTIAGO FILHO' , 'Email' : 'dep.wilsonfilho@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WLADIMIR AFONSO DA COSTA RABELO' , 'Email' : 'dep.wladimircosta@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'WOLNEY QUEIROZ MACIEL' , 'Email' : 'dep.wolneyqueiroz@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'YEDA RORATO CRUSIUS' , 'Email' : 'dep.yedacrusius@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'},
    {'Nome' : 'JOSÉ AUGUSTO NALIN' , 'Email' : 'dep.zeaugustonalin@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ CARLOS NUNES JÚNIOR' , 'Email' : 'dep.zecarlos@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ GERALDO TORRES DA SILVA' , 'Email' : 'dep.zegeraldo@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ SILVA SOARES' , 'Email' : 'dep.zesilva@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSE CAVALCANTI ALVES JUNIOR' , 'Email' : 'dep.zecacavalcanti@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSÉ CARLOS BECKER DE OLIVEIRA E SILVA' , 'Email' : 'dep.zecadirceu@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'JOSE ORCIRIO MIRANDA DOS SANTOS' , 'Email' : 'dep.zecadopt@camara.leg.br' , 'Tratamento' : 'Exmo. Senhor Deputado'},
    {'Nome' : 'ZENAIDE MAIA CALADO PEREIRA DOS SANTOS' , 'Email' : 'dep.zenaidemaia@camara.leg.br' , 'Tratamento' : 'Exma. Senhora Deputada'}
)




for deputado in deputados:
    print(deputado['Email'] + " " + deputado['Nome'] + " " + deputado['Tratamento'])


    if len(deputado) > 0:
        msg = MIMEMultipart()
        msg['subject'] = 'Reserva Nacional de Cobre e Associados'
        parte1 = '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title></title>
	<meta name="generator" content="LibreOffice 5.1.6.2 (Linux)"/>
	<meta name="created" content="2017-08-27T11:36:26.023591307"/>
	<meta name="changed" content="2017-08-27T12:24:27.893451363"/>
	<style type="text/css">
		@page { margin: 2cm }
		p { margin-bottom: 0.25cm; line-height: 120% }
		a:link { so-language: zxx }
	</style>
</head>
<body lang="pt-BR" dir="ltr">
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><font color="#0066cc"><font size="6" style="font-size: 26pt"><b>'''
        parte2 = '''Ao %s %s''' % (deputado['Tratamento'], deputado['Nome'])

        parte3 = '''</b></font></font></p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><font color="#800000"><font size="4" style="font-size: 16pt"><b>A
extinsão da Renca por decreto é um CRIME.</b></font></font></p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><font color="#800000"><font size="5" style="font-size: 18pt"><b>Diga
não!!!!!! Vamos precionar o presidente Temer!</b></font></font></p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><font color="#007826"><font size="4" style="font-size: 15pt"><b>Abaixo
um artigo que demonstra a importância da vegetação para o CLIMA
LOCAL e periférico!!!!!!!!!!!</b></font></font></p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><font color="#007826"><font size="4" style="font-size: 15pt"><b>Todos
os brasileiros serão atingidos por este decreto!!!!!!!</b></font></font></p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><a href="http://www.cdcc.usp.br/maomassa/mostras/2014/Trabalho%20pdf/1_A_arvore_traz_a_chuva.pdf"><font color="#007826"><font size="4" style="font-size: 15pt"><b>http://www.cdcc.usp.br/maomassa/mostras/2014/Trabalho%20pdf/1_A_arvore_traz_a_chuva.pdf</b></font></font></a></p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><font color="#007826"><font size="4" style="font-size: 15pt"><b>Enviaremos
estes e-mails com artigos cientificos todos os dias até que o
decreto seja revisto!!!!</b></font></font></p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p align="center" style="margin-bottom: 0cm; line-height: 100%"><font color="#007826"><font size="7" style="font-size: 48pt"><b>Não
desistiremos!</b></font></font></p>
</body>
</html>'''
        conteudo = parte1 + parte2 + parte3

        msg.attach(MIMEText(conteudo, 'html'))
        mailer = smtplib.SMTP('smtp.gmail.com', 587)
        mailer.ehlo()
        mailer.starttls()
        mailer.ehlo()
        mailer.login('falandocomdeputado@gmail.com', 'senha!@#')
        mailer.sendmail('falandocomdeputado@gmail.com', deputado['Email'], msg.as_string())
        mailer.close()